# Generated by Django 6.0.4 on 2026-04-13 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=50, unique=True)),
                ('audio_file', models.CharField(max_length=255)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(default='de', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caller_first_name', models.CharField(blank=True, max_length=100)),
                ('caller_last_name', models.CharField(blank=True, max_length=100)),
                ('caller_email', models.EmailField(blank=True, max_length=254)),
                ('caller_phone', models.CharField(blank=True, max_length=50)),
                ('urgency', models.PositiveSmallIntegerField(blank=True, help_text='1 (low) to 5 (critical)', null=True)),
                ('key_facts', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('resolution_status', models.CharField(choices=[('resolved', 'Resolved'), ('needs_followup', 'Needs Follow-up'), ('appointment_booked', 'Appointment Booked'), ('dropped', 'Dropped / Abandoned'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('lead_score', models.PositiveSmallIntegerField(blank=True, help_text='0-100', null=True)),
                ('lead_score_reasoning', models.TextField(blank=True)),
                ('resolution_gaps', models.JSONField(blank=True, default=list)),
                ('playbook_completeness', models.FloatField(blank=True, help_text='0.0 to 1.0', null=True)),
                ('confidence_scores', models.JSONField(blank=True, default=dict, help_text='Per-field confidence, e.g. {"first_name": 0.9, "email": 0.6}')),
                ('needs_human_review', models.BooleanField(default=False)),
                ('extraction_accuracy', models.JSONField(blank=True, default=dict, help_text='Per-field match vs ground_truth, e.g. {"first_name": true}')),
                ('case_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.casetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playbook', to='calls.casetype')),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='calls.playbook')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('whisper_model', models.CharField(default='base', max_length=50)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='calls.call')),
            ],
        ),
    ]
