# Generated by Django 6.0.4 on 2026-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='playbook_answered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='playbook_unanswered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='call',
            name='recommended_actions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
