# Generated by Django 6.0.4 on 2026-04-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_playbook_answered_call_playbook_unanswered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='quality_audit',
            field=models.JSONField(blank=True, default=dict, help_text='LLM-as-Judge audit result: quality_score, verdict, issues, hallucinated_fields'),
        ),
        migrations.AddField(
            model_name='call',
            name='reflection_applied',
            field=models.BooleanField(default=False, help_text='True if Agent 2 re-extracted low-confidence fields'),
        ),
        migrations.AddField(
            model_name='call',
            name='tool_corrections',
            field=models.JSONField(blank=True, default=list, help_text='List of corrections applied by deterministic tools (email validator, phone formatter)'),
        ),
    ]
